name: Messaging Library Tests

on: push

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        paho: ["1.6.1", "2.1.0"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Start Mosquitto broker
        run: |
          docker run -d --name mqtt -p 11883:10003 \
            -v $GITHUB_WORKSPACE/cluster_orchestrator/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro \
            eclipse-mosquitto:2.0

      - name: Install library and test dependencies
        run: |
          pip install ./libraries/oakestra_messaging pytest
          pip install "paho-mqtt==${{ matrix.paho }}"

      - name: Run test suite
        working-directory: libraries/oakestra_messaging
        env:
          OAKESTRA_TEST_MQTT_ADDR: 127.0.0.1:11883
        run: |
          pytest -v
